name: Update this repo's README

on: [push]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: JasonEtco/rss-to-readme@v2
        with:
          feed-url: https://jasonet.co/rss.xml
          readme-section: feed
          path: 'profile/README.md'
          template: '* [{{ pubDate | date("YYYY-MM-DD") }}] - [{{ title }}]({{ link }}))'
